# Generated by Django 3.2.12 on 2022-06-08 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import donut.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=2000)),
                ('date', models.DateTimeField(default=donut.models.default_datetime)),
                ('likes', models.IntegerField(default=0)),
                ('img', models.ImageField(upload_to='posts/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=100)),
                ('count_posts', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('followers', models.IntegerField(default=0)),
                ('img', models.ImageField(default='images/default.png', upload_to='images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
