# Generated by Django 3.2.12 on 2022-04-05 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donut', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='img',
        ),
    ]
