# Generated by Django 3.2.12 on 2022-06-09 07:40

from django.db import migrations, models
import donut.models


class Migration(migrations.Migration):

    dependencies = [
        ('donut', '0003_likespost_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='likespost',
            name='data',
            field=models.DateTimeField(default=donut.models.default_datetime),
        ),
    ]
