# Generated by Django 3.2.12 on 2022-06-09 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donut', '0004_likespost_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likespost',
            old_name='check',
            new_name='like',
        ),
    ]
