# Generated by Django 3.2.12 on 2022-04-09 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donut', '0003_profile'),
        ('donut', '0004_auto_20220409_1141'),
    ]

    operations = [
    ]
