# Generated by Django 3.2.12 on 2022-04-09 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donut', '0005_merge_0003_profile_0004_auto_20220409_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customusers',
            old_name='posts',
            new_name='count_posts',
        ),
        migrations.AlterField(
            model_name='customusers',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
