# Generated by Django 3.2.12 on 2022-04-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donut', '0006_auto_20220409_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='img',
            field=models.ImageField(default='static/img/default.png', upload_to='images/'),
        ),
    ]
