# Generated by Django 3.2.12 on 2022-06-10 12:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donut', '0008_auto_20220609_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusers',
            name='followers',
        ),
        migrations.AddField(
            model_name='customusers',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='likespost',
            name='value',
            field=models.CharField(choices=[('Unlike', 'Unlike'), ('Like', 'Like')], default='Like', max_length=10),
        ),
    ]
