# Generated by Django 3.2.12 on 2022-04-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donut', '0008_alter_customusers_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='img',
            field=models.ImageField(default='/images/default.png', upload_to='images/'),
        ),
    ]
