# Generated by Django 3.2.12 on 2022-06-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donut', '0009_auto_20220610_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusers',
            name='followers',
        ),
        migrations.AddField(
            model_name='customusers',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='likespost',
            name='value',
            field=models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='Like', max_length=10),
        ),
    ]
