# Generated by Django 3.2.12 on 2022-04-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donut', '0010_alter_customusers_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusers',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customusers',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customusers',
            name='password',
        ),
        migrations.AddField(
            model_name='customusers',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customusers',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
