# Generated by Django 3.2.12 on 2022-06-11 07:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donut', '0011_alter_likespost_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusers',
            name='followers',
        ),
        migrations.AddField(
            model_name='customusers',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='likespost',
            name='value',
            field=models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='Like', max_length=10),
        ),
    ]
