# Generated by Django 3.2.12 on 2022-04-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donut', '0011_auto_20220409_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='name',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
