# Generated by Django 3.2.12 on 2022-06-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donut', '0012_auto_20220611_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusers',
            name='following',
        ),
        migrations.AddField(
            model_name='customusers',
            name='followers',
            field=models.IntegerField(default=0),
        ),
    ]
