# Generated by Django 3.2.12 on 2022-06-11 07:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donut', '0013_auto_20220611_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusers',
            name='followers',
        ),
        migrations.AddField(
            model_name='customusers',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
