# Generated by Django 3.2.12 on 2022-06-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donut', '0014_auto_20220611_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likespost',
            name='value',
            field=models.CharField(choices=[('Unlike', 'Unlike'), ('Like', 'Like')], default='Like', max_length=10),
        ),
    ]
