# Generated by Django 3.2.12 on 2022-06-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donut', '0017_auto_20220616_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='male',
            field=models.CharField(choices=[('female', 'FEMALE'), ('male', 'MALE')], default='male', max_length=6),
        ),
        migrations.AlterField(
            model_name='likespost',
            name='value',
            field=models.CharField(choices=[('Unlike', 'Unlike'), ('Like', 'Like')], default='Like', max_length=10),
        ),
    ]
