# Generated by Django 3.2.12 on 2022-05-02 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donut', '0017_posts_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='date',
        ),
    ]
