# Generated by Django 3.2.12 on 2022-06-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donut', '0018_auto_20220620_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='customusers',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='profile_views', to='donut.IpModel'),
        ),
    ]
