# Generated by Django 3.2.12 on 2022-06-22 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donut', '0019_auto_20220622_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusers',
            name='views',
        ),
        migrations.DeleteModel(
            name='IpModel',
        ),
    ]
