# Generated by Django 3.2.12 on 2022-05-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donut', '0019_posts_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='img',
            field=models.ImageField(upload_to='posts/', verbose_name='Photo'),
        ),
    ]
