# Generated by Django 3.2.12 on 2022-05-06 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donut', '0020_alter_posts_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='img',
            new_name='photo',
        ),
    ]
