# Generated by Django 3.2.12 on 2022-05-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donut', '0021_rename_img_posts_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name': 'photo'},
        ),
        migrations.AlterField(
            model_name='posts',
            name='photo',
            field=models.ImageField(upload_to='posts/', verbose_name='photo'),
        ),
    ]
