# Generated by Django 3.2.12 on 2022-05-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donut', '0022_auto_20220506_1028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={},
        ),
        migrations.AlterField(
            model_name='posts',
            name='photo',
            field=models.ImageField(upload_to='posts/', verbose_name='Photo'),
        ),
    ]
