# Generated by Django 3.2.12 on 2022-05-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donut', '0023_auto_20220506_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='photo',
            field=models.ImageField(upload_to='posts/'),
        ),
    ]
