# Generated by Django 3.2.12 on 2022-05-06 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donut', '0024_alter_posts_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='photo',
            new_name='img',
        ),
    ]
